### ISSUE TITLE
README.md is inaccurate 

### ISSUE THREAD

**Issue by somethingconcon** [qingwei91/basil#9]
Hi,

I attempted to follow the direction of the README to do a simple implementation.

`
    object SearchEngine {

      def searchEngine = new SearchEngine {
        import basil.data.ParseOpsConstructor._
        import basil.parser.implicits._
        import basil.parser._

        def findTarget(document: String, nodeName: String) = {
          Parser.parseString(
            Start.getKey(nodeName).getString,
            document)
        }
      }
    }
`

Which produces errors:

> [info] Loading project definition from /Users/conorreedy/Dropbox/dank-memes/scala/transformer/project
> [info] Set current project to Mapping stuff (in build file:/Users/conorreedy/Dropbox/dank-memes/scala/transformer/)
> [info] Compiling 5 Scala sources to /Users/conorreedy/Dropbox/dank-memes/scala/transformer/target/scala-2.12/classes...
> [error] /Users/conorreedy/Dropbox/dank-memes/scala/transformer/src/main/scala/interpreters/Fuse.scala:44: value eval is not a member of basil.data.ExprEnd[basil.data.ParseOps,String]
> [error]         Start.getKey(n).getString.eval,
> [error]                                   ^
> [error] /Users/conorreedy/Dropbox/dank-memes/scala/transformer/src/main/scala/interpreters/Fuse.scala:39: Unused import
> [error]     import basil.parser.implicits._
> [error]                                   ^
> [error] two errors found
> [error] (compile:compileIncremental) Compilation failed
> [error] Total time: 5 s, completed Dec 21, 2018 3:25:56 PM

In looking through the source I believe I have implemented this correctly.  What am I missing?

Thank you!

**Comment by qingwei91** [comment]
Hi @somethingconcon 

thanks for reporting, I've updated the readme

can you try to update the version to 0.0.3, and change your import from 
`import basil.data.ParseOpsConstructor._`  to `import basil.syntax.ParseOpsConstructor._` to see if that solves the issue?
